apiVersion: 1

datasources:
  - name: Prometheus
    uid: prom
    type: prometheus
    access: proxy
    url: http://prometheus:9090
  - name: Tempo
    uid: temp
    type: tempo
    access: proxy
    url: http://tempo:3200
  - name: Loki
    uid: lok
    type: loki
    access: proxy
    url: http://loki:3100