receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889" 
    namespace: "otelcol"

  loki:
    endpoint: ${LOKI_ENDPOINT}

  otlp:
    endpoint: ${TEMPO_ENDPOINT}
    tls:
      insecure: true

extensions:
  health_check:
    endpoint: "0.0.0.0:13133"

  zpages:
    endpoint: "0.0.0.0:55679"

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]

    metrics:
      receivers: [otlp]
      exporters: [prometheus]

    logs:
      receivers: [otlp]
      exporters: [loki]
