name: Backend Build Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore .NET dependencies
        run: |
          for proj in $(find . -name "*.csproj" ! -path "./helpers/*"); do
            dotnet restore $proj
          done

      - name: Build .NET projects
        run: |
          for proj in $(find . -name "*.csproj" ! -path "./helpers/*"); do
            dotnet build $proj --configuration Release /p:TreatWarningsAsErrors=true
          done
