name: Docker Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Fix permissions for MinIO init script
        run: chmod +x ./init-minio.sh || true

      - name: Build and run Docker Compose
        run: |
          docker compose up --build -d
